default_platform(:android)

platform :android do
  desc "Incrementar versión, firmar y desplegar a Google Play Store"
  lane :deploy do
    # Establecer la página de códigos UTF-8
    ENV['LANG'] = 'en_US.UTF-8'

    # Obtener e incrementar versionCode y versionName
    version_code = android_get_version_code(
      gradle_file: "./app/build.gradle"
    ) + 1

    version_name = android_get_version_name(
      gradle_file: "./app/build.gradle"
    ).split('.').tap do |parts|
      parts[-1] = (parts.last.to_i + 1).to_s
    end.join('.')

    android_set_version_code(
      gradle_file: "./app/build.gradle",
      version_code: version_code
    )

    android_set_version_name(
      gradle_file: "./app/build.gradle",
      version_name: version_name
    )

    # Configurar la firma
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV['MYAPP_UPLOAD_STORE_FILE'],
        "android.injected.signing.store.password" => ENV['MYAPP_UPLOAD_STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['MYAPP_UPLOAD_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['MYAPP_UPLOAD_KEY_PASSWORD']
      }
    )

    # Subir a Google Play Store
    upload_to_play_store(
      track: 'production',
      json_key: 'C:/Users/ispm1/OneDrive/Escritorio/React-Native-Todo-List/android/testtodolist-423618-a33659dc86ef.json',
      package_name: 'com.projecttwo.ispmgodrd'
    )
  end
end
