name: Deploy Android App

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build Signed AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 20

    - name: Setup Gradle Cache
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Bump Version Code
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{ github.run_number }}
        versionName: 1.0.0

    - name: Build Release
      run: gradle bundleRelease
