name: CI

on:
  push:
    branches: -""
    
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Node.js dependencies
      run: npm install

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install

    - name: Create missing xcconfig files
      run: |
        touch ios/Pods/Target\ Support\ Files/Pods-projectTwo/Pods-projectTwo.debug.xcconfig
        touch ios/Pods/Target\ Support\ Files/Pods-projectTwo-projectTwoTests/Pods-projectTwo-projectTwoTests.debug.xcconfig

    - name: Build the iOS app
      run: |
        xcodebuild -workspace ios/projectTwo.xcworkspace \
                   -scheme projectTwo \
                   -configuration Debug \
                   -sdk iphonesimulator \
                   -derivedDataPath ios/build
