name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Signed AAB
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20

      - name: Run Yarn Install
        run: |
          npm i -g corepack
          yarn install

      - name: List directory contents
        run: ls -l
        working-directory: ${{ github.workspace }}/android

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ${{ github.workspace }}/android

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Bump Version Code
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: ${{ github.workspace }}/android/build.gradle
          versionCode: '${{ github.run_number }}'
          versionName: 1.0.0

      - name: Build application
        run: |
          cd android
          ./gradlew bundleRelease
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      
      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: ./android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 3

  deploy:
    name: Deploy aab to Playstore
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download app bundle from artifact
        uses: actions/download-artifact@v2
        with:
          name: app-release.aab
          path: app-release.aab
      
      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.projecttwo
          releaseFiles: app-release.aab
          track: production
